dataset:
  image_dir: ./data/butterfly
  img_size: 512
  name: butterfly
  num_samples: 100000
  classes: ["Monarch", "Viceroy"]

file_list_paths: 
  - ./file_lists/file_list_butterfly_target0.txt
  - ./file_lists/file_list_butterfly_target1.txt
  
batch_size: 1
num_inference_steps: 100
num_images: 10000
device: 1 
output_dir: ./outputs
eval_clf_weights: ./classifier/butterfly
clip_image_embeds_dir: ./data/clip_image_embeds/butterfly
embed_filenames: ["class0_embeds", "class1_embeds"]
lora_weights_dir: null

