dataset:
  name: kermany
  image_dir: ./data/kermany
  classes: ["DRUSEN", "NORMAL"]
  img_size: 512

file_list_paths: 
  - ./file_list_short/file_list_kermany_target0.txt
  - ./file_list_short/file_list_kermany_target1.txt

batch_size: 1
num_inference_steps: 100
num_images: 10000
device: 3 
output_dir: ./output
eval_clf_weights: ./classifier/kermany
clip_image_embeds_dir: ./data/clip_image_embeds/kermany 
embed_filenames: ["0_val", "1_val"]
lora_weights_dir: null

